# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Ccalc_mROC_stats <- function(M, Y) {
    .Call(`_mROC_Ccalc_mROC_stats`, M, Y)
}

Csimulate_null_mROC_stats_unconditional <- function(M, n_sim) {
    .Call(`_mROC_Csimulate_null_mROC_stats_unconditional`, M, n_sim)
}

